### ISSUE TITLE
branches from gitorious missing

### ISSUE THREAD

**Issue by planthaber** [rock-simulation/imumodel#2]
Hi,

the "stable", and "rock1408" repos were not copied ti this new location

**Comment by goldhoorn** [comment]
On 19.03.2015 14:07, Steffen Planthaber wrote:

> Hi,
> 
> the "stable", and "rock1408" repos were not copied ti this new location
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rock-simulation/imumodel/issues/2.
> 
> I hav no clou how is taking care about that.
> Can you provide me the source/original repro and i can try to push the 
> missing branches upwards (as long there a re no conflicts)

Best,
Matthias

## 

  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany

  Zentrale: +49 421 178 45-6611

  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany

  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by planthaber** [comment]
git@gitorious.org:rock-simulation/imumodel.git
git@gitorious.org:rock-simulation/orogen-imumodel.git

please also add the tags (for the other branches):  git push --tags new-origin

**Comment by goldhoorn** [comment]
assume this is fixed
